image:
  registry: docker.io
  repository: bitnami/apache
  tag: 2.4.46-debian-10-r32
  pullPolicy: IfNotPresent
  debug: false
git:
  registry: docker.io
  repository: bitnami/git
  tag: 2.28.0-debian-10-r43
  pullPolicy: IfNotPresent
replicaCount: 1
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: ""
  key: ""
  values: []
affinity: {}
nodeSelector: {}
tolerations: []
cloneHtdocsFromGit:
  enabled: false
  interval: 60
  resources: {}
podAnnotations: {}
resources:
  limits: {}
  requests: {}
livenessProbe:
  enabled: true
  path: "/"
  port: http
  initialDelaySeconds: 180
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  path: "/"
  port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
ingress:
  enabled: false
  certManager: false
  hostname: example.local
  annotations: {}
  tls:
    - hosts:
        - example.local
      secretName: example.local-tls
  secrets:
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/apache-exporter
    tag: 0.8.0-debian-10-r154
    pullPolicy: IfNotPresent
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
  resources:
    limits: {}
    requests: {}
service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  nodePorts:
    http: ""
    https: ""
  annotations: {}
  externalTrafficPolicy: Cluster
